### ISSUE TITLE
只能解密到这种程度还是不能完全解密

### ISSUE THREAD

**Issue by jaychoubaby** [smallfawn/decode_action#28]
你好，我fork后按照步骤操作揭秘了一下js，结果发现解密完还有很多不可读代码，请问是只能解密到这样还是需要再自己编译一下？![image](https://github.com/smallfawn/decode_action/assets/26641387/b5edc4a4-fce7-4f90-9375-d4703f4b66b2)

**Comment by smallfawn** [comment]
这个就是最终的结果啊  你还看不懂啊
